os: Visual Studio 2017

version: 1.0.6.{build}

configuration:
- Debug

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
- ps: Start-FileDownload 'https://download.microsoft.com/download/1/4/1/141760B3-805B-4583-B17C-8C5BC5A876AB/Installers/dotnet-dev-win-x64.1.0.0-preview2-1-003177.exe'
- cmd: dotnet-dev-win-x64.1.0.0-preview2-1-003177.exe /quiet

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\
  COVERALLS_REPO_TOKEN:
    secure: tsTABRbCmdWFLT194XNIrpurerOfjN6cEoxt2RaSUfLmUIgra/+CwuqVkv0sPRop

build_script:
- appveyor-retry dotnet restore .\src\System.Linq.Dynamic.Core -v Minimal
- appveyor-retry dotnet restore .\src\EntityFramework.DynamicLinq -v Minimal
- appveyor-retry dotnet restore .\src\Microsoft.EntityFrameworkCore.DynamicLinq -v Minimal

- appveyor-retry dotnet restore .\test\System.Linq.Dynamic.Core.Tests  -v Minimal
- appveyor-retry dotnet restore .\test\EntityFramework.DynamicLinq.Tests  -v Minimal


- dotnet build .\src\System.Linq.Dynamic.Core\project.json -c %CONFIGURATION%
- dotnet build .\src\EntityFramework.DynamicLinq\project.json -c %CONFIGURATION%
- dotnet build .\src\Microsoft.EntityFrameworkCore.DynamicLinq\project.json -c %CONFIGURATION%

- dotnet build .\test\System.Linq.Dynamic.Core.Tests\project.json -c %CONFIGURATION%
- dotnet build .\test\EntityFramework.DynamicLinq.Tests\project.json -c %CONFIGURATION%

- dotnet pack -c Release --no-build --version-suffix %LABEL% -o .\artifacts .\src\System.Linq.Dynamic.Core\project.json
- dotnet pack -c Release --no-build --version-suffix %LABEL% -o .\artifacts .\src\EntityFramework.DynamicLinq\project.json
- dotnet pack -c Release --no-build --version-suffix %LABEL% -o .\artifacts .\src\Microsoft.EntityFrameworkCore.DynamicLinq\project.json

test_script:
- dotnet test -c %CONFIGURATION% --no-build .\test\System.Linq.Dynamic.Core.Tests
- dotnet test -c %CONFIGURATION% --no-build .\test\EntityFramework.DynamicLinq.Tests

after_test:
  - nuget.exe install OpenCover -ExcludeVersion
  - nuget.exe install coveralls.net -ExcludeVersion
  - OpenCover\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"\".\test\EntityFramework.DynamicLinq.Tests\bin\%CONFIGURATION%\net461\win7-x64\EntityFramework.DynamicLinq.Tests.dll\" -noshadow -appveyor" -returntargetcode -filter:"+[System.Linq.Dynamic.Core]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -searchdirs:"\".\test\EntityFramework.DynamicLinq.Tests\bin\%CONFIGURATION%\net461\win7-x64\"" -output:coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
  - coveralls.net\tools\csmacnz.Coveralls.exe --opencover -i .\coverage.xml

artifacts:
- path: artifacts\**\*.*

cache:
- '%USERPROFILE%\.nuget\packages'