os: Visual Studio 2015

version: 1.0.3.{build}

configuration:
- Debug
- Release

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe'
- cmd: dotnet-dev-win-x64.latest.exe /quiet

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\

build_script:
- appveyor-retry dotnet restore .\src\System.Linq.Dynamic.Core -v Minimal
- appveyor-retry dotnet restore .\src\EntityFramework.DynamicLinq -v Minimal
- appveyor-retry dotnet restore .\src\Microsoft.EntityFrameworkCore.DynamicLinq -v Minimal
- appveyor-retry dotnet restore .\test\System.Linq.Dynamic.Core.Tests  -v Minimal

- dotnet build src\System.Linq.Dynamic.Core\project.json -c %CONFIGURATION%
- dotnet build src\EntityFramework.DynamicLinq\project.json -c %CONFIGURATION%
- dotnet build src\Microsoft.EntityFrameworkCore.DynamicLinq\project.json -c %CONFIGURATION%
- dotnet build test\System.Linq.Dynamic.Core.Tests\project.json -c %CONFIGURATION%

- dotnet pack -c Release --no-build --version-suffix %LABEL% -o .\artifacts .\src\System.Linq.Dynamic.Core\project.json
- dotnet pack -c Release --no-build --version-suffix %LABEL% -o .\artifacts .\src\EntityFramework.DynamicLinq\project.json
- dotnet pack -c Release --no-build --version-suffix %LABEL% -o .\artifacts .\src\Microsoft.EntityFrameworkCore.DynamicLinq\project.json

test_script:
- dotnet test -c %CONFIGURATION% --no-build .\test\System.Linq.Dynamic.Core.Tests

artifacts:
- path: artifacts\**\*.*

cache:
- '%USERPROFILE%\.nuget\packages'