os: Visual Studio 2017

version: 1.0.7.{build}

configuration:
- Debug

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
  - ps: Start-FileDownload 'https://download.microsoft.com/download/8/F/9/8F9659B9-E628-4D1A-B6BF-C3004C8C954B/dotnet-1.1.1-sdk-win-x64.exe'
  - cmd: dotnet-1.1.1-sdk-win-x64.exe /quiet
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "true"

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\
  COVERALLS_REPO_TOKEN:
    secure: tsTABRbCmdWFLT194XNIrpurerOfjN6cEoxt2RaSUfLmUIgra/+CwuqVkv0sPRop

build_script:
# Restore all
- dotnet restore src\System.Linq.Dynamic.Core\System.Linq.Dynamic.Core.csproj
- dotnet restore src\EntityFramework.DynamicLinq\EntityFramework.DynamicLinq.csproj
- dotnet restore src\Microsoft.EntityFrameworkCore.DynamicLinq\Microsoft.EntityFrameworkCore.DynamicLinq.csproj

- dotnet restore test\System.Linq.Dynamic.Core.Tests\System.Linq.Dynamic.Core.Tests.csproj
- dotnet restore test\EntityFramework.DynamicLinq.Tests\EntityFramework.DynamicLinq.Tests.csproj

# Build Code
- dotnet build src\System.Linq.Dynamic.Core\System.Linq.Dynamic.Core.csproj -c %CONFIGURATION% --framework netstandard1.3
- dotnet build src\EntityFramework.DynamicLinq\EntityFramework.DynamicLinq.csproj -c %CONFIGURATION%
- dotnet build src\Microsoft.EntityFrameworkCore.DynamicLinq\Microsoft.EntityFrameworkCore.DynamicLinq.csproj -c %CONFIGURATION% --framework netstandard1.3

# Build Tests
- dotnet build test\System.Linq.Dynamic.Core.Tests\System.Linq.Dynamic.Core.Tests.csproj -c %CONFIGURATION%
- dotnet build test\EntityFramework.DynamicLinq.Tests\EntityFramework.DynamicLinq.Tests.csproj -c %CONFIGURATION%

test_script:
- dotnet test -c %CONFIGURATION% --no-build test\System.Linq.Dynamic.Core.Tests\System.Linq.Dynamic.Core.Tests.csproj
- dotnet test -c %CONFIGURATION% --no-build test\EntityFramework.DynamicLinq.Tests\EntityFramework.DynamicLinq.Tests.csproj

after_test:
  - nuget.exe install OpenCover -ExcludeVersion
  - nuget.exe install coveralls.net -ExcludeVersion
  - pip install codecov

  - cmd: '"OpenCover\tools\OpenCover.Console.exe" -target:dotnet.exe -targetargs:"test test\System.Linq.Dynamic.Core.Tests\System.Linq.Dynamic.Core.Tests.csproj --configuration %CONFIGURATION% --framework netcoreapp1.1 --no-build" -output:coverage.xml -register:user -filter:"+[*]* -[*NFluent*]*" -returntargetcode -oldstyle'
  - codecov -f "coverage.xml"
  - coveralls.net\tools\csmacnz.Coveralls.exe --opencover -i .\coverage.xml