os: Visual Studio 2015

install:
- dnvm upgrade -r clr
- dnu restore

build:
  verbosity: minimal

build_script:
- cmd: dnu build src\System.Linq.Dynamic.Core
- cmd: msbuild src\System.Linq.Dynamic.Core.SL50
- cmd: dnu build test\System.Linq.Dynamic.Core.Tests

test_script:
- cmd: dnx -p test/System.Linq.Dynamic.Core.Tests test